spring:
  application:
    name: DBH_ACADEMY
  datasource:
    url: jdbc:mysql://${DB_HOSTNAME:localhost}:3306/BDD_FIREACADEMY?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: 'firefight'
    password: 'firefight'
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate #create the rirst time change to validate in production mode
      use-new-id-generator-mappings: false #prevents HHH90000014: Found use of deprecated [org.hibernate.id.SequenceHiLoGenerator] sequence-based id generator; use org.hibernate.id.enhanced.SequenceStyleGenerator instead.  See Hibernate Domain Model Mapping Guide for details.
    show-sql: false
  data:
    rest:
      base-path: /api/v1

server:
  port: ${PORT:3000}   # HTTP (Tomcat) port

logging:
  #  pattern:
  #    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework.web: WARN
    org.hibernate: INFO
    com.dbhacademy.firefight: WARN

